org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=bookmarks.json, campus.json, categories.json, edges_MAP-01.json, edges_MAP-02.json, google-services-desktop.json, indoor.json, indoor_edges.json, infrastructure.json, maps.json, nodes_MAP-01.json, nodes_MAP-02.json, recent_destinations.json, static_data_cache.json, version_cache_MAP-01.json, version_cache_MAP-02.json
unityTemplateVersion=7
android.useAndroidX=true
android.enableJetifier=true
org.gradle.welcome=never
android.aapt2FromMavenOverride=/home/yazar/Unity/2022.3.62f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/build-tools/34.0.0/aapt2