org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
unityStreamingAssets=bookmarks.json, campus.json, categories.json, edges_MAP-01.json, edges_MAP-02.json, google-services-desktop.json, indoor.json, indoor_edges.json, infrastructure.json, maps.json, nodes_MAP-01.json, nodes_MAP-02.json, recent_destinations.json, static_data_cache.json, version_cache_MAP-01.json, version_cache_MAP-02.json
unityTemplateVersion=7
